name = "fern"
version = "0.1.0"
defaultTargets = ["Fern"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"

[[lean_lib]]
name = "Fern"
weakLeanOptions = {"experimental.module" = true}

[[lean_exe]]
name = "fern-exe"
root = "Main"
