name = "baelean"
version = "0.1.0"
defaultTargets = ["baelean"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"

[[lean_lib]]
name = "baelean"
weakLeanOptions = {"experimental.module" = true}

[[lean_exe]]
name = "baelean-exe"
root = "Main"
